apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseerr
  namespace: {{ .Release.Namespace }}
spec:
  defaultBackend:
    service:
      name: jellyfin
      port:
        name: jellyseerr
  ingressClassName: tailscale
  tls:
    - hosts:
        - jellyseerr.west-beta.ts.net
