tailscale_repo_url: https://pkgs.tailscale.com/helmcharts
tailscale_version: 1.76.6
tailscale_namespace: tailscale
tailscale_values:
  oauth:
    clientId: "{{ tailscale_client_id }}"
    clientSecret: "{{ tailscale_client_secret }}"
  apiServerProxyConfig:
    mode: true
