rustfs:
  mode:
    standalone:
      enabled: true
    distributed:
      enabled: false
  secret:
    rustfs:
      access_key: rustfsadmin
      secret_key: zsd4lsRZHeD9I0OX2pr2I2HBCkzsuot9sFegcbmP5Co=
  storageclass:
    name: standard-rwo
    dataStorageSize: 1Gi
    logStorageSize: 1Gi
  ingress:
    className: tailscale
    customAnnotations:
      tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
    hosts:
      - host: rustfs.west-beta.ts.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      enabled: true
      # 其实是因为tailscale也是自动生成证书的
      # 这样配置避免tls secret的创建
      certManager:
        enabled: true

  config:
    rustfs:
      log_level: "info"
      rust_log: "info"
  service:
    type: ClusterIP

  gatewayApi:
    gatewayClass: ""
